/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csv.utils;

import org.junit.Test;

import example.ExampleModel;

import static org.junit.Assert.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CsvUtilsTest {
    @Test public void testConvertToCsv() {
    	LocalDateTime now = LocalDateTime.now();
    	String nowString = now.format(DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"));
    	String expected = "ID,FirstName,LastName,Age,CreatedAt" + 
    			"1,Taro,Yamada,30," + nowString + 
    			"2,Jiro,Tanaka,25," + nowString;
    	
    	
    	List<ExampleModel> models = new ArrayList<>(
    			Arrays.asList(
    				new ExampleModel(1, "Taro", "Yamada", 30, now),
    				new ExampleModel(2, "Jiro", "Tanaka", 25, now)
    			)
    	);
    	String actual = CsvUtils.convertToCsv(models, ExampleModel.class);
    	actual = actual.replace("\r\n ","");
    	actual = actual.replace("\r","");
    	actual = actual.replace("\n","");
    	
    	assertEquals(expected, actual);
     }
}
